### ISSUE TITLE
No catching of exceptions in the IDE

### ISSUE THREAD

**Issue by gbracha** [newspeaklanguage/newspeak#71]
Bugs in IDE code cause the system to crash rather than opening a debugger.

**Comment by mzimmerm** [comment]
FWIW, here is a scenario that reproduces this problem:  First I added a line with "break." to  "Browsing>>ObjectPresenter>>helpText" just before the return line. Clicking the Help "?" on an instance link in Workspace clearly hits that break. But it did not take me to debugger at all as far as I can tell - it shoved me back where I was, Workspace, with a stack trace below it. Is it perhaps because this is in the UI thread or something? Attaching the result.

![break-not-working-not-hit-when-in-helpText](https://user-images.githubusercontent.com/1468540/127431513-3f54ad8d-4440-48e1-9d04-25a181fc663e.png)

**Comment by gbracha** [comment]
Fixed.
